	tilepal 0, GRAY, GRAY, BROWN, GRAY, GRAY, GRAY, WATER, BROWN
	tilepal 0, BROWN, GRAY, WATER, WATER, WATER, WATER, GRAY, WATER
	tilepal 0, WATER, RED, BROWN, GRAY, GRAY, GRAY, WATER, BROWN
	tilepal 0, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, WATER, WATER, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, RED, WATER, WATER, WATER, WATER, RED
	tilepal 1, RED, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 1, GRAY, RED, RED, WATER, WATER, WATER, WATER, RED
	tilepal 1, RED, GRAY, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 1, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, BROWN, BROWN, YELLOW, YELLOW, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, BROWN, BROWN, YELLOW, YELLOW, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
